name: z_arrows
description: "Z-Arrows — Shift the Arrows, Clear the Maze."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  flame_audio: ^2.1.0
  shared_preferences: ^2.5.5
  google_mobile_ads: ^9.0.0
  in_app_purchase: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/shapes/
