"""Assigns each campaign country a visa-stamp shape, ink colour and caption.

One stamp per country, generated by an image model and shipped as a baked
asset. No clear date is printed — a date would make every stamp unique per
player and force runtime compositing; without it the 216 images are static
files that need no code at all.

The assignment is deterministic so a re-run does not reshuffle stamps players
have already collected, and the three attributes cycle on periods that share
no common factor, so a combination repeats only every lcm(4, 6, 5) = 60
rounds. Neighbouring rounds are seen side by side on the world map, so runs of
near-identical stamps are what this is avoiding.

Output: stamp_plan.json  [{rank, name, ko, continent, shape, ink, hex,
                           caption, prompt}]
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
CAMPAIGN = os.path.join(REPO, "assets", "campaign", "campaign.json")
OUT = os.path.join(HERE, "stamp_plan.json")

SHAPES = [
    ("circle", "perfect CIRCLE with a double concentric ring"),
    ("square", "SQUARE with slightly rounded corners"),
    ("rect", "wide horizontal RECTANGLE, passport entry-stamp proportions"),
    ("diamond", "DIAMOND — a square rotated 45 degrees, straight edges, "
                "no circular ring inside it"),
]

# Inks real passport stamps are actually struck in.
COLOURS = [
    ("blue", "deep cobalt blue", "#2F6BFF"),
    ("red", "brick red", "#C0392F"),
    ("green", "forest green", "#2E6B4F"),
    ("violet", "ink violet", "#5B4A9E"),
    ("black", "off-black ink", "#23252E"),
    ("teal", "dark teal", "#1F6F78"),
]

CAPTIONS = ["VISITED", "EXPLORED", "UNLOCKED", "COMPLETED", "DISCOVERED"]

# Islands a country's outline is wrong without. Only entries the user has
# called out get one — guessing at contested territory is not our call.
EXTRA_DETAIL = {
    "South Korea":
        "JEJU island as one small oval below the southwest tip; ULLEUNGDO as "
        "a small SOLID dot off the east coast; and DOKDO as a slightly "
        "smaller SOLID dot further east than Ulleungdo and a little lower, "
        "clearly separated from it, the easternmost mark on the stamp. Draw "
        "both islands at full ink strength so they read as land, not as "
        "specks of stamp wear",
}


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def prompt_for(name, shape_desc, colour_desc, caption, extra):
    detail = f" Include {extra}." if extra else ""
    return (
        f"A single passport visa rubber stamp, centred on warm off-white "
        f"paper.\n\n"
        f"Outline: {shape_desc}.\n\n"
        f"Inside the stamp, all in ONE ink colour:\n"
        f"- the map of {name} as a solid filled silhouette in the centre, "
        f"geographically accurate in proportion and coastline.{detail}\n"
        f"- the country name {name.upper()} in bold condensed uppercase "
        f"sans-serif\n"
        f"- the single word {caption}\n\n"
        f"Print NO date, year, number or serial anywhere on the stamp.\n\n"
        f"Layout: the map and all lettering sit WELL INSIDE the outline with "
        f"clear margin on every side. Nothing touches, overlaps or crosses "
        f"the border. The map is fully contained — never cropped by the "
        f"frame.\n\n"
        f"Style: authentic worn rubber stamp impression in {colour_desc}. "
        f"Uneven ink coverage, patchy gaps where the rubber missed the paper, "
        f"slightly bleeding edges, fine grain, one side pressed harder than "
        f"the other. Stamped at a slight tilt as if by hand. Crisp legible "
        f"typography despite the wear. Flat 2D graphic — no photographic 3D, "
        f"no shadows, no gradients, no watercolour. Plain paper background "
        f"with subtle fibre texture. Nothing else on the page."
    )


def main():
    countries = load(CAMPAIGN)["countries"]
    rows = []
    for c in countries:
        rank = c["rank"]
        shape, shape_desc = SHAPES[(rank - 1) % len(SHAPES)]
        ink, colour_desc, hexv = COLOURS[(rank - 1) % len(COLOURS)]
        caption = CAPTIONS[(rank - 1) % len(CAPTIONS)]
        rows.append({
            "rank": rank,
            "name": c["name"],
            "ko": c.get("ko", c["name"]),
            "continent": c.get("continent", ""),
            "shape": shape,
            "ink": ink,
            "hex": hexv,
            "caption": caption,
            "file": f"stamp_{rank:03d}_{c['name'].lower().replace(' ', '_')}.png",
            "prompt": prompt_for(c["name"], shape_desc, colour_desc, caption,
                                 EXTRA_DETAIL.get(c["name"])),
        })

    with open(OUT, "w", encoding="utf-8") as f:
        json.dump({"stamps": rows}, f, ensure_ascii=False, indent=1)

    from collections import Counter
    print(f"국가 {len(rows)}개")
    print("형상:", dict(Counter(r["shape"] for r in rows)))
    print("색상:", dict(Counter(r["ink"] for r in rows)))
    print("문구:", dict(Counter(r["caption"] for r in rows)))
    print("\n앞 8개:")
    for r in rows[:8]:
        print(f"  {r['rank']:>3} {r['ko']:<14}{r['shape']:<9}"
              f"{r['ink']:<8}{r['caption']}")
    print(f"\n-> {OUT}")


if __name__ == "__main__":
    main()
